"""pirmas

Revision ID: 8e2a91dc2577
Revises: 
Create Date: 2022-02-27 18:25:11.200014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2a91dc2577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vartotojas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Vardas', sa.String(length=200), nullable=False),
    sa.Column('Pavarde', sa.String(length=200), nullable=False),
    sa.Column('El.pastas', sa.String(length=200), nullable=False),
    sa.Column('Slaptazodis', sa.String(length=200), nullable=False),
    sa.Column('Administratorius', sa.Boolean(), nullable=True),
    sa.Column('Prisijungimo_vardas', sa.String(length=20), nullable=False),
    sa.Column('Vartotojo_tipas', sa.String(length=20), nullable=False),
    sa.Column('Yra_darbuotojas', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('El.pastas'),
    sa.UniqueConstraint('Prisijungimo_vardas')
    )
    op.create_table('automobilis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Marke', sa.String(length=200), nullable=True),
    sa.Column('Modelis', sa.String(length=200), nullable=True),
    sa.Column('Variklis', sa.String(length=200), nullable=True),
    sa.Column('Vin numeris', sa.String(length=200), nullable=True),
    sa.Column('Valstybinis numeris', sa.String(length=200), nullable=True),
    sa.Column('vartotojas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vartotojas_id'], ['vartotojas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('irasas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Sukurta', sa.DateTime(), nullable=True),
    sa.Column('Suma', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('Tekstas', sa.String(length=200), nullable=True),
    sa.Column('automobilis_id', sa.Integer(), nullable=True),
    sa.Column('Remonto_Statusas', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['automobilis_id'], ['automobilis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('irasas')
    op.drop_table('automobilis')
    op.drop_table('vartotojas')
    # ### end Alembic commands ###
